version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      # name: version
      # name: version
    commands:
       - wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb 
       - sudo dpkg -i packages-microsoft-prod.deb 
       - sudo apt-get update; sudo apt-get install -y apt-transport-https && sudo apt-get update && sudo apt-get install -y dotnet-sdk-6.0 
       - sudo apt install aspnetcore-runtime-6.0=6.0.8-1 -y --allow-downgrades
       - sudo apt install dotnet-apphost-pack-6.0=6.0.8-1 -y --allow-downgrades
       - sudo apt install dotnet-host=6.0.8-1 -y --allow-downgrades
       - sudo apt install dotnet-hostfxr-6.0=6.0.8-1 -y --allow-downgrades
       - sudo apt install dotnet-runtime-6.0=6.0.8-1 -y --allow-downgrades
       - sudo apt install dotnet-sdk-6.0=6.0.400-1  -y --allow-downgrades
       - sudo apt install dotnet-targeting-pack-6.0=6.0.8-1 -y --allow-downgrades
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - pwd
      - ls
      - dotnet --version
      - dotnet restore pkversity.sln
      - dotnet publish pkversity.sln
  #post_build:
    #commands:
      # - command
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
  files:
     - '**/*'

     
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
