version: '3.4'

networks:
   pkversity:
services:

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=awab123@@
    build:
      context: .
      dockerfile: SqlServer/Dockerfile
    networks:
      - pkversity

  admin:
    container_name: admin
    image: ${DOCKER_REGISTRY-}admin
    build:
      context: .
      dockerfile: Admin/Dockerfile
    depends_on:
      - sqlserver
    environment:
       - DB_HOST=sqlserver
    networks:
      - pkversity
  
  university:
    container_name: university
    image: ${DOCKER_REGISTRY-}university
    build:
      context: .
      dockerfile: University/Dockerfile
    depends_on:
        - sqlserver
    environment:
       - DB_HOST=sqlserver
    networks:
     - pkversity

  user:
    container_name: user
    image: ${DOCKER_REGISTRY-}user
    build:
      context: .
      dockerfile: User/Dockerfile
    depends_on:
      - sqlserver
    environment:
       - DB_HOST=sqlserver
    networks:
      - pkversity