version: '3.4'

services:
  admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  university:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  user:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

